## Promise使用

#### 1.Promise 是一个构造函数， new Promise 返回一个 promise对象 接收一个excutor执行函数作为参数, excutor有两个函数类型形参resolve reject

```js
const promise = new Promise((resolve, reject) => {
       // 异步处理
       // 处理结束后、调用resolve 或 reject
});

```

#### 2.promise相当于一个状态机

promise的三种状态

- pending
- fulfilled
- rejected

1.promise 对象初始化状态为 pending
 2.当调用resolve(成功)，会由pending => fulfilled
 3.当调用reject(失败)，会由pending => rejected

> 注意promsie状态 只能由 pending => fulfilled/rejected, 一旦修

#### 3.promise对象方法

1.then方法注册 当resolve(成功)/reject(失败)的回调函数

```js
// onFulfilled 是用来接收promise成功的值
// onRejected 是用来接收promise失败的原因
promise.then(onFulfilled, onRejected);
//then方法是异步执行的
```

2.resolve(成功) onFulfilled会被调用



```tsx
const promise = new Promise((resolve, reject) => {
   resolve('fulfilled'); // 状态由 pending => fulfilled
});
promise.then(result => { // onFulfilled
    console.log(result); // 'fulfilled' 
}, reason => { // onRejected 不会被调用
    
})
```

3.reject(失败) onRejected会被调用



```tsx
const promise = new Promise((resolve, reject) => {
   reject('rejected'); // 状态由 pending => rejected
});
promise.then(result => { // onFulfilled 不会被调用
  
}, reason => { // onRejected 
    console.log(rejected); // 'rejected'
})
```

4.promise.catch

> 在链式写法中可以捕获前面then中发送的异常,



```csharp
promise.catch(onRejected)
相当于
promise.then(null, onRrejected);

// 注意
// onRejected 不能捕获当前onFulfilled中的异常
promise.then(onFulfilled, onRrejected); 

// 可以写成：
promise.then(onFulfilled)
       .catch(onRrejected);   
```

#### 4.promise chain

> promise.then方法每次调用 都返回一个新的promise对象 所以可以链式写法



```jsx
function taskA() {
    console.log("Task A");
}
function taskB() {
    console.log("Task B");
}
function onRejected(error) {
    console.log("Catch Error: A or B", error);
}

var promise = Promise.resolve();
promise
    .then(taskA)
    .then(taskB)
    .catch(onRejected) // 捕获前面then方法中的异常
```

#### 5.Promise的静态方法

1.Promise.resolve 返回一个fulfilled状态的promise对象



```jsx
Promise.resolve('hello').then(function(value){
    console.log(value);
});

Promise.resolve('hello');
// 相当于
const promise = new Promise(resolve => {
   resolve('hello');
});
```

2.Promise.reject 返回一个rejected状态的promise对象



```jsx
Promise.reject(24);
new Promise((resolve, reject) => {
   reject(24);
});
```

3.Promise.all 接收一个promise对象数组为参数

> 只有全部为resolve才会调用 通常会用来处理 多个并行异步操作



```tsx
const p1 = new Promise((resolve, reject) => {
    resolve(1);
});

const p2 = new Promise((resolve, reject) => {
    resolve(2);
});

const p3 = new Promise((resolve, reject) => {
    reject(3);
});

Promise.all([p1, p2, p3]).then(data => { 
    console.log(data); // [1, 2, 3] 结果顺序和promise实例数组顺序是一致的
}, err => {
    console.log(err);
});
```

4.Promise.race 接收一个promise对象数组为参数

> Promise.race 只要有一个promise对象进入 FulFilled 或者 Rejected 状态的话，就会继续进行后面的处理。



```jsx
function timerPromisefy(delay) {
    return new Promise(function (resolve, reject) {
        setTimeout(function () {
            resolve(delay);
        }, delay);
    });
}
var startDate = Date.now();

Promise.race([
    timerPromisefy(10),
    timerPromisefy(20),
    timerPromisefy(30)
]).then(function (values) {
    console.log(values); // 10
});
```